### ISSUE TITLE
Error in colab

### ISSUE THREAD

**Issue by shenzy08** [yilundu/cross_attention_renderer#1]
I run the code in the colab, and encounter the below error. Please help me fix it. Thank you!
![image](https://user-images.githubusercontent.com/58035336/232694693-94c6066a-ef88-4c0b-b2e1-4ddb03ab6ccd.png)

**Comment by shenzy08** [comment]
![image](https://user-images.githubusercontent.com/58035336/232695230-de2d73b1-905f-426a-a18d-a24174adf807.png)

**Comment by yilundu** [comment]
Hi sorry, thanks for catching this! I accidentally forgot to uncomment one line in the colab -- should be fixed now.

**Comment by shenzy08** [comment]
It works now! 
One another problem: some files are missing, such as vis_realestate10k_traj.py and test_unposed_traj.py,

**Comment by yilundu** [comment]
Thanks for catching that! I updated the file names -- do you still have errors?

**Comment by shenzy08** [comment]
Yes, I ran the script 
python experiment_scripts/eval_realestate10k.py --experiment_name vis_realestate --batch_size 12 --gpus 1 --checkpoint_path logs/realestate/checkpoints/model_current.pth
and then 
FileNotFoundError: [Errno 2] No such file or directory: 'poses/realestate/test.mat'

**Comment by yilundu** [comment]
Did you download the necessary data? It should be downloaded here: https://www.dropbox.com/s/qo8b7odsms722kq/cvpr2023_wide_baseline_data.tar.gz?dl=0

**Comment by shenzy08** [comment]
Thank you for your remind. I ran the code in the google colab, but cannot get the results as good as that in your project page.
https://user-images.githubusercontent.com/58035336/233262223-55e6fb39-6f65-4556-8220-a0f451156477.mp4
https://user-images.githubusercontent.com/58035336/233262238-fde8443b-2095-4072-9fe0-c488f7b956c2.mp4
Can you help to check it?

**Comment by yilundu** [comment]
Hi -- thanks for checking this. The results in the webpage are using an older version of codebase -- as I was cleaning and refactoring the code I had to train a new version of the model. I believe the results on the Realestate10k video is similar to the one on the website. For the unposed images -- with the newly trained model -- I couldn't get as smooth interpolations between the same images -- my guess is that retraining a new model with a different scale on the L2 depth_loss would probably get a bit smoother interpolation (the interpolations will also be a bit smoother if you tune the translation offset between the two unposed images).

I'm happy to potentially share the older codebase / model if you are interested in getting the same result on the unposed images.

**Comment by shenzy08** [comment]
Ok. I am looking forward to trying the older model, which seems much more awesome.

**Comment by yilundu** [comment]
Sure -- I'll attach the older codebase in a separate branch with a demo code to generate the unposed trajectory in the next day.
