### ISSUE TITLE
Regarding square crop

### ISSUE THREAD

**Issue by SunghwanHong** [yilundu/cross_attention_renderer#2]
Hi, Thanks for sharing such wonderful work!

I have a small question regarding the square crop function. 
So if my understanding is correct, in the augmentation, you use 'center square crop', but square crop (256x256) is a default setting for both training and evaluation?

I found the code lines that performs square crops at training time, but I'm not sure if you do the same at evaluation as well.

Do you square crop at evaluation as well?

Thanks!

**Comment by yilundu** [comment]
Yes, we use a center crop for both training and evaluation.

**Comment by SunghwanHong** [comment]
Thanks for the quick reply!

For clarification, I thought you use 'center crop' for augmentation, but 'square crop' for both training and evaluation preprocessing. Is this right?

**Comment by yilundu** [comment]
Ahh sorry yes let me clarify. Images are cropped to squares in both training and evaluation preprocessing. Center crop augmentation is further applied at training, but is not applied at evaluation.
