### ISSUE TITLE
Train / test splits of ACID dataset

### ISSUE THREAD

**Issue by takerum** [yilundu/cross_attention_renderer#3]
Hi, thank you for sharing the reproducing code!
I am trying to download the ACID videos, but I found no explicit train/test split information in the ACID pose files downloaded from the link in the downloaders README. Could you tell me the train/test splits of ACID used to get the results in the paper?

**Comment by yilundu** [comment]
Hi for the ACID dataset -- I believe the original poses have a train/test/validation split -- I used that split for train and test

**Comment by takerum** [comment]
Please let me make sure: there are two ACID pose datasets: ACID and ACID Large. The latter is downloaded from the link on the Readme page and only contains one directory, in which there are 13177 .txt files in total. I looked at some of them but could only find a URL to a video and poses in each .txt file. (I paste below the directory structure shown with the `tree` command)
The former is available on [the authors' page ](https://infinite-nature.github.io/#:~:text=%5B-,Download%20ACID,-%5D) and it actually has train/test/valid split in it, but the number of txt files in each directory is not even close to numbers in your paper (2026 for train, 2512 for val and 11225 for test while your paper says 11075 and 1972 scenes are used for train and test set respectively.)

I am guessing the directory structure of ACID Large has changed at some point, but I would very much appreciate it if you could point out if I am missing something.

<img width="291" alt="image" src="https://github.com/yilundu/cross_attention_renderer/assets/11573649/785fcf45-90ef-44bd-9e5f-2595fb62ddf9">

**Comment by yilundu** [comment]
Ahh I see -- can you try the camera poses here? https://www.dropbox.com/s/ml511k9nx0gff0e/acid_poses.tar.gz?dl=0

**Comment by takerum** [comment]
Thanks, but I guess the poses are for RealEstate? I see the numbers of the files are 71559 in train and 7714 in test directory.

**Comment by yilundu** [comment]
Oh my bad -- can you try this link again, I believe I have updated the zip? https://www.dropbox.com/s/ml511k9nx0gff0e/acid_poses.tar.gz?dl=0

**Comment by takerum** [comment]
Yes, it's updated, and the files seem to be the ACID ones. Thank you!
