### ISSUE TITLE
Mat file for realestate10K poses

### ISSUE THREAD

**Issue by tedyhabtegebrial** [yilundu/cross_attention_renderer#7]
Dear @yilundu,
thanks for your work. I was looking for the realestate10K poses which should be in .mat format.
Could you please share it with me ?

Thanks!
Tewodros

**Comment by yilundu** [comment]
Sure, you can find the training poses at https://www.dropbox.com/scl/fi/74cplj898b1r6zuqsojob/realestate_train.mat?rlkey=udm1p5fildr21odk38yjlis4a&dl=0 and test poses at https://www.dropbox.com/scl/fi/4crmo6w2dck3e2dg7e062/realestate_test.mat?rlkey=1zbasxxfgtksgb08pxizuffcp&dl=0

**Comment by tedyhabtegebrial** [comment]
Thanks a lot!

**Comment by tedyhabtegebrial** [comment]
closing the  issue
