### ISSUE TITLE
Mapping not support in python3.10 in colab

### ISSUE THREAD

**Issue by visonpon** [yilundu/cross_attention_renderer#8]
hi, thanks for sharing this wonderful work, i got error in colab since the initial python is 3.10, ut mapping not support in python3.10

**Comment by yilundu** [comment]
Hi, thank you for your comment -- could you paste the error you get?

**Comment by visonpon** [comment]
I got error` AttributeError: module 'collections' has no attribute 'Mapping'`. 
I also tried to build the env on my machine and test , but got typeerror: 
```
nrender = model_input['query']['cam2world'].size(1)
'CrossAttentionRender' object is not subscriptable
```

**Comment by yilundu** [comment]
Hi I pushed an update -- can you see if that works?

**Comment by visonpon** [comment]
it works, thanks~
